// borutoVoice.js
// ---------------------------------------------------------------------------
// Boruto Uzumaki voice-line pools (audio-only; NO gameplay effect). TWO COMPLETELY SEPARATE pools:
//   BORUTO_VOICE       — BASE form (boruto_main_*.mp3, 163 clips + 23 split sub-lines)
//   BORUTO_KARMA_VOICE — MOMOSHIKI KARMA form (boruto_karma_*.mp3, 49 clips) — NEVER mixed with base.
// Clips are UNIDENTIFIED JAPANESE (silence-gap segmented from source compilations; no transcript/translation
// possible), so assignment is by ACOUSTIC SIGNAL ONLY (duration / loudness / pitch via
// tools/analyze_boruto_voice.py → boruto_{main,karma}_voice_analysis.tsv), NOT by content — FLAGGED for
// by-ear confirmation. pickBorutoVoice(pool) / pickBorutoKarmaVoice(pool) return ONE clip at random; callers
// play via sound.playSfxFile(clip, null).
//
// FLAGGED LONG BASE CLIPS: the 12 clips flagged as 7-11s (likely multi-line, music-masked pauses) were
// gap-analyzed; the 9 with detectable internal gaps were SPLIT at gap midpoints → boruto_main_<NNNx>.mp3
// (a/b/c segments). The 3 with NO detectable gaps (002/012/041 — music fully masks the pauses) are kept
// WHOLE and used only in the ULT pool (a long dramatic line is fine there). Re-cut by ear if boundaries surface.
//
// KARMA success/failure ARE audibly distinct (different files + different acoustic signature): absorbSuccess
// = mid confident clips (~2.6-3.1s, f0~150Hz); absorbFail = short strained/high-tension grunts (~0.6-1.4s,
// f0~300Hz+). Generated by tools/gen_boruto_voice_js.py.
// ---------------------------------------------------------------------------

export const BORUTO_VOICE = {
  intro: ["./boruto_main_001_0000.0s.mp3", "./boruto_main_007_0032.2s.mp3", "./boruto_main_024_0114.9s.mp3", "./boruto_main_025_0119.5s.mp3", "./boruto_main_030_0144.7s.mp3", "./boruto_main_050_0237.8s.mp3", "./boruto_main_059_0279.4s.mp3", "./boruto_main_082_0356.0s.mp3", "./boruto_main_122_0475.0s.mp3", "./boruto_main_123_0479.4s.mp3"],
  lightEffort: ["./boruto_main_003_0012.9s.mp3", "./boruto_main_011_0053.3s.mp3", "./boruto_main_046_0213.4s.mp3", "./boruto_main_103_0419.3s.mp3", "./boruto_main_118_0462.0s.mp3", "./boruto_main_124_0484.0s.mp3", "./boruto_main_130_0507.5s.mp3", "./boruto_main_134_0518.0s.mp3", "./boruto_main_153_0566.5s.mp3", "./boruto_main_162_0595.4s.mp3"],
  heavy: ["./boruto_main_015_0075.6s.mp3", "./boruto_main_016_0078.1s.mp3", "./boruto_main_020_0100.1s.mp3", "./boruto_main_026_0123.9s.mp3", "./boruto_main_027_0126.0s.mp3", "./boruto_main_031_0148.8s.mp3", "./boruto_main_140_0529.8s.mp3", "./boruto_main_144_0546.4s.mp3"],
  rasenganGround: ["./boruto_main_006_0029.3s.mp3", "./boruto_main_010_0050.1s.mp3", "./boruto_main_021_0102.4s.mp3", "./boruto_main_033_0158.4s.mp3", "./boruto_main_055_0262.8s.mp3", "./boruto_main_057_0272.8s.mp3"],
  rasenganAir: ["./boruto_main_075_0330.3s.mp3", "./boruto_main_081_0352.5s.mp3", "./boruto_main_084_0364.8s.mp3", "./boruto_main_085_0367.1s.mp3", "./boruto_main_145_0548.4s.mp3", "./boruto_main_146_0550.7s.mp3"],
  vanishing: ["./boruto_main_060_0283.7s.mp3", "./boruto_main_061_0287.4s.mp3", "./boruto_main_063_0292.4s.mp3", "./boruto_main_091_0384.6s.mp3", "./boruto_main_094_0394.8s.mp3"],
  shiden: ["./boruto_main_018_0087.3s.mp3", "./boruto_main_023_0111.3s.mp3", "./boruto_main_038_0177.3s.mp3", "./boruto_main_051_0242.1s.mp3", "./boruto_main_086_0370.4s.mp3", "./boruto_main_045_0211.3s.mp3", "./boruto_main_058_0276.5s.mp3"],
  windWater: ["./boruto_main_088_0376.5s.mp3", "./boruto_main_089_0379.6s.mp3", "./boruto_main_108_0436.9s.mp3", "./boruto_main_117_0458.6s.mp3", "./boruto_main_076_0333.0s.mp3", "./boruto_main_087_0374.6s.mp3"],
  shadowClone: ["./boruto_main_120_0466.0s.mp3", "./boruto_main_126_0489.4s.mp3", "./boruto_main_128_0498.5s.mp3", "./boruto_main_131_0509.1s.mp3", "./boruto_main_142_0539.4s.mp3"],
  throwWeapon: ["./boruto_main_035_0167.4s.mp3", "./boruto_main_036_0168.8s.mp3", "./boruto_main_039_0181.4s.mp3", "./boruto_main_040_0182.8s.mp3", "./boruto_main_043_0201.0s.mp3", "./boruto_main_062_0290.6s.mp3"],
  ult: ["./boruto_main_041_0185.1s.mp3", "./boruto_main_002_0004.3s.mp3", "./boruto_main_012_0054.8s.mp3", "./boruto_main_019b.mp3", "./boruto_main_047b.mp3", "./boruto_main_028a.mp3", "./boruto_main_052b.mp3", "./boruto_main_077b.mp3"],
  hitLight: ["./boruto_main_080_0351.7s.mp3", "./boruto_main_096_0401.9s.mp3", "./boruto_main_109_0440.9s.mp3", "./boruto_main_111_0444.0s.mp3", "./boruto_main_139_0528.3s.mp3", "./boruto_main_152_0565.5s.mp3", "./boruto_main_137_0524.2s.mp3", "./boruto_main_079_0350.3s.mp3", "./boruto_main_157_0578.4s.mp3", "./boruto_main_161_0594.0s.mp3"],
  hitHeavy: ["./boruto_main_099_0407.0s.mp3", "./boruto_main_115_0453.2s.mp3", "./boruto_main_132_0513.8s.mp3", "./boruto_main_133_0515.7s.mp3", "./boruto_main_135_0519.8s.mp3", "./boruto_main_138_0525.6s.mp3", "./boruto_main_147_0553.2s.mp3", "./boruto_main_148_0554.7s.mp3"],
  knockdown: ["./boruto_main_072_0326.0s.mp3", "./boruto_main_073_0327.3s.mp3", "./boruto_main_074_0329.0s.mp3", "./boruto_main_093_0392.8s.mp3", "./boruto_main_100_0409.3s.mp3", "./boruto_main_112_0444.6s.mp3", "./boruto_main_136_0521.5s.mp3", "./boruto_main_154_0567.7s.mp3"],
  win: ["./boruto_main_009_0044.4s.mp3", "./boruto_main_013_0062.5s.mp3", "./boruto_main_022_0105.5s.mp3", "./boruto_main_029_0139.7s.mp3", "./boruto_main_034_0161.3s.mp3", "./boruto_main_042_0195.7s.mp3", "./boruto_main_078_0343.7s.mp3", "./boruto_main_155_0570.1s.mp3", "./boruto_main_092_0387.5s.mp3", "./boruto_main_102_0414.3s.mp3"],
}

export const BORUTO_KARMA_VOICE = {
  transform: ["./boruto_karma_011_0041.1s.mp3", "./boruto_karma_049_0159.6s.mp3", "./boruto_karma_004_0011.7s.mp3", "./boruto_karma_022_0082.4s.mp3", "./boruto_karma_005_0017.3s.mp3"],
  absorbSuccess: ["./boruto_karma_008_0031.4s.mp3", "./boruto_karma_002_0005.7s.mp3", "./boruto_karma_048_0155.2s.mp3", "./boruto_karma_024_0088.7s.mp3", "./boruto_karma_006_0022.0s.mp3"],
  absorbFail: ["./boruto_karma_034_0119.2s.mp3", "./boruto_karma_040_0133.7s.mp3", "./boruto_karma_038_0129.3s.mp3", "./boruto_karma_033_0117.3s.mp3"],
  hit: ["./boruto_karma_023_0087.2s.mp3", "./boruto_karma_036_0123.9s.mp3", "./boruto_karma_037_0126.5s.mp3", "./boruto_karma_047_0153.3s.mp3", "./boruto_karma_009_0036.0s.mp3", "./boruto_karma_015_0056.5s.mp3", "./boruto_karma_029_0107.5s.mp3"],
  revert: ["./boruto_karma_030_0109.8s.mp3", "./boruto_karma_035_0121.2s.mp3"],
}

export function pickBorutoVoice(pool) {
  const arr = BORUTO_VOICE[pool]
  if (!Array.isArray(arr) || arr.length === 0) return null
  return arr[Math.floor(Math.random() * arr.length)]
}

export function pickBorutoKarmaVoice(pool) {
  const arr = BORUTO_KARMA_VOICE[pool]
  if (!Array.isArray(arr) || arr.length === 0) return null
  return arr[Math.floor(Math.random() * arr.length)]
}
