// preloadManifest.js
// Stage 10 — curated registry of projectile / FX / alternate-FORM body sheets that live as inline
// literals inside abilities.js (there is no central registry there). These are the sheets that fault
// to the _FALLBACK box on their FIRST use — worst during ultimates/transforms, exactly when they spawn.
// preloadFighter() already covers a character's base + skin body sheets from characters.animationData;
// THIS covers everything abilities.js spawns that the base walk never sees.
//
// Attributed by sheet-name prefix (see tools/check_fx_manifest.mjs, the drift guard that regenerates
// this list from abilities.js and fails if any spawned .png is unlisted). Over-listing is harmless
// (it just warms a sheet that may go unused); under-listing reintroduces the first-use fault.
//
// NOTE ON CACHING: FX sheets are drawn via ui.js / per-cinematic private image caches, NOT sprite.js's
// _cache. Decoding them here warms the BROWSER HTTP cache so the eventual (separate) Image load resolves
// from cache instead of the network — the pragmatic 90% fix without unifying every FX cache.

export const FX_SHEETS_BY_CHAR = {
  batman: [
    "./batman_baterang_proj.png",
  ],
  beerus: [
    "./beerus_downward_fx_u.png",
    "./beerus_hakai_fx_u.png",
    "./beerus_ki_blast_fx_u.png",
    "./beerus_push_ring1_u.png",
    "./beerus_push_ring2_u.png",
  ],
  chrollo: [
    "./chrollo_nenbeast_uniform.png",
  ],
  gojo: [
    "./gojo_blue_orb_fx.png",
    "./gojo_hollow_purple_orb_fx.png",
    "./gojo_red_orb_fx.png",
  ],
  goku_black: [
    "./goku_black_ssj_rose_charge_uniform.png",
    "./goku_black_ssj_rose_dash.png",
    "./goku_black_ssj_rose_down_attack.png",
    "./goku_black_ssj_rose_electric_ki_push.png",
    "./goku_black_ssj_rose_electric_ki_push_effect.png",
    "./goku_black_ssj_rose_electric_slash.png",
    "./goku_black_ssj_rose_foward_attack.png",
    "./goku_black_ssj_rose_gaurd.png",
    "./goku_black_ssj_rose_get_up.png",
    "./goku_black_ssj_rose_hit.png",
    "./goku_black_ssj_rose_idle.png",
    "./goku_black_ssj_rose_idle_2.png",
    "./goku_black_ssj_rose_jump.pmg.png",
    "./goku_black_ssj_rose_kamehameha.png",
    "./goku_black_ssj_rose_ki_slash.png",
    "./goku_black_ssj_rose_run.png",
    "./goku_black_ssj_rose_spirit_bomb.png",
    "./goku_black_ssj_rose_super_ki_slash.png",
    "./goku_black_ssj_rose_sword_slahs_Special.png",
    "./goku_black_ssj_rose_up_attack.png",
  ],
  gold_samurai_ranger: [
    "./samurai_ranger_gold_mega_aerial_uniform.png",
    "./samurai_ranger_gold_mega_guard_uniform.png",
    "./samurai_ranger_gold_mega_launcher_uniform.png",
    "./samurai_ranger_gold_mega_mode_bjump_uniform.png",
    "./samurai_ranger_gold_mega_mode_hurt_uniform.png",
    "./samurai_ranger_gold_mega_mode_idle_uniform.png",
    "./samurai_ranger_gold_mega_mode_run_uniform.png",
    "./samurai_ranger_gold_mega_rising_uniform.png",
    "./samurai_ranger_gold_mega_slash_uniform.png",
    "./samurai_ranger_gold_slashwave_uniform.png",
  ],
  green_samurai_ranger: [
    "./samurai_ranger_forest_mega_guard_uniform.png",
    "./samurai_ranger_forest_mega_idle_uniform.png",
    "./samurai_ranger_forest_mega_jump_uniform.png",
    "./samurai_ranger_forest_mega_launcher_uniform.png",
    "./samurai_ranger_forest_mega_lunge_uniform.png",
    "./samurai_ranger_forest_mega_rising_uniform.png",
    "./samurai_ranger_forest_mega_run_uniform.png",
    "./samurai_ranger_forest_mega_slash_uniform.png",
    "./samurai_ranger_forest_mega_spear_cast_uniform.png",
    "./samurai_ranger_forest_spear_wave_uniform.png",
  ],
  hisoka: [
    "./hisoka_card_projectile_uniform.png",
    "./hisoka_powerup_idle_uniform.png",
    "./hisoka_powerup_up_uniform.png",
  ],
  ichigo: [
    "./ichigo_getsuga_proj.png",
  ],
  itachi: [
    "./itachi_amaterasu_flame_uniform.png",
    "./itachi_fireball_proj_uniform.png",
    "./itachi_susano_creature_attack_uniform.png",
    "./itachi_susano_creature_block_uniform.png",
    "./itachi_susano_creature_idle.png",
    "./itachi_susano_creature_sword_effect.png",
    "./itachi_susano_creature_sword_uniform.png",
    "./itachi_susano_creature_took_damage_uniform.png",
  ],
  killua: [
    "./killua_yoyo_fx.png",
  ],
  madara: [
    "./madara2_fireball_proj_uniform.png",
    "./madara2_gunbai_slash_fx_uniform.png",
    "./madara2_susanoo_grab_air_uniform.png",
    "./madara2_wood_spike_proj_uniform.png",
    "./madara_complete_atk1_uniform.png",
    "./madara_complete_atk2_uniform.png",
    "./madara_complete_idle_uniform.png",
    "./madara_susanoo_form_atk1_uniform.png",
    "./madara_susanoo_form_atk2_uniform.png",
    "./madara_susanoo_form_idle_uniform.png",
    "./madara_wood_dragon_burst_uniform.png",
    "./madara_wood_dragon_proj_uniform.png",
  ],
  maki: [
    "./maki_kunai_proj.png",
    "./maki_shibuya_air_covered.png",
    "./maki_shibuya_downair_covered.png",
    "./maki_shibuya_g1_covered.png",
    "./maki_shibuya_g2_covered.png",
    "./maki_shibuya_g3_covered.png",
    "./maki_shibuya_heavy_covered.png",
    "./maki_shibuya_idle_covered.png",
    "./maki_shibuya_intro_covered.png",
    "./maki_shibuya_jump_covered.png",
    "./maki_shibuya_light_covered.png",
    "./maki_shibuya_run_covered.png",
    "./maki_shibuya_up_covered.png",
  ],
  minato: [
    "./minato_big_ball_uniform.png",
    "./minato_kunai_projectile.png",
    "./minato_rasengan_orb_uniform.png",
    "./minato_reaper_death_seal_fire_uniform.png",
    "./minato_reaper_death_seal_summoning_arm_uniform.png",
    "./minato_reaper_death_seal_summoning_uniform.png",
    "./minato_yellow_flash_teleport.png",
  ],
  naruto: [
    "./naruto_kcm_fx_fox_left.png",
    "./naruto_kcm_fx_fox_right.png",
    "./naruto_kcm_fx_rasengan_sphere.png",
    "./naruto_kcm_fx_rasenshuriken.png",
    "./naruto_kcm_fx_tbb_shockwave_2.png",
  ],
  netero: [
    "./guanyin_arm_sweep_uniform.png",
    "./guanyin_combo_slash_uniform.png",
    "./guanyin_idle_uniform.png",
    "./guanyin_leg_strike_uniform.png",
    "./guanyin_punch_burst_uniform.png",
    "./guanyin_run_lunge_uniform.png",
    "./netero_guanyin_guard_big.png",
    "./netero_guanyin_hurt_big.png",
  ],
  nezuko: [
    "./nezuko_ball_kick_projectile.png.png",
    "./nezuko_tanjiro_assist.png",
    "./nezuko_zenistu_assit.png",
  ],
  obito: [
    "./masked_man_chain_smash_fx_uniform.png",
    "./masked_man_fire_explosion_uniform.png",
    "./masked_man_fire_giant_uniform.png",
    "./masked_man_fire_sub_uniform.png",
    "./masked_man_kamui_portalfx_uniform.png",
    "./masked_man_kunia_proj_uniform.png",
    "./obito_giantshur_proj_uniform.png",
    "./obito_portalfx.png",
    "./obito_rod_throwprojectile.png.png",
    "./obito_shur_proj_uniform.png",
  ],
  omega_ranger: [
    "./omega_ranger_gun_bolt_uniform.png",
  ],
  rick: [
    "./rick_rocket_specail.png",
  ],
  saiki: [
    "./saiki_bolt_bot_u.png",
    "./saiki_bolt_top_u.png",
    "./saiki_bomb_fx_u.png",
    "./saiki_burst_fx_u.png",
    "./saiki_chain1_fx_u.png",
    "./saiki_chain2_fx_u.png",
    "./saiki_chain3_fx_u.png",
    "./saiki_chainfin_fx_u.png",
  ],
  samurai_red_ranger: [
    "./samurai_ranger_flameburst_uniform.png",
    "./samurai_ranger_flameslash_uniform.png",
    "./samurai_ranger_mega_combo_uniform.png",
    "./samurai_ranger_mega_downattack_2_uniform.png",
    "./samurai_ranger_mega_downattack_uniform.png",
    "./samurai_ranger_mega_guard_uniform.png",
    "./samurai_ranger_mega_hit_uniform.png",
    "./samurai_ranger_mega_idle_uniform.png",
    "./samurai_ranger_mega_jump_uniform.png",
    "./samurai_ranger_mega_ultimate_uniform.png",
    "./samurai_ranger_mega_upattack_1_uniform.png",
    "./samurai_ranger_mega_upattack_2_uniform.png",
    "./samurai_ranger_mega_walk_uniform.png",
  ],
  sasuke: [
    "./sasuke_CHIDORI_KOITEN_effects.png",
    "./sasuke_lighting_attack_repeatable.png",
    "./sasuke_shuriken.png",
    "./sasuke_substitusion_justu.png",
    "./sasuke_summon.png",
    "./sasuke_susanoo_arrow_attack.png",
    "./sasuke_susanoo_grab.png",
    "./sasuke_susanoo_intro.png",
    "./sasuke_susanoo_lvl_1_anim.png",
    "./sasuke_susanoo_lvl_2_anim.png",
    "./sasuke_susanoo_sword_attack.png",
  ],
  vegeta: [
    "./vegeta_base_bigbang_fx_uniform.png",
    "./vegeta_base_finalflash_beam1_uniform.png",
    "./vegeta_base_galick_fx_uniform.png",
    "./vegeta_base_kiblast_orb_uniform.png",
    "./vegeta_blue_air_uniform.png",
    "./vegeta_blue_bigbang_fx_uniform.png",
    "./vegeta_blue_charge_up_uniform.png",
    "./vegeta_blue_cmd_uniform.png",
    "./vegeta_blue_finalflash_beam_uniform.png",
    "./vegeta_blue_galick_cast_uniform.png",
    "./vegeta_blue_galick_fx_uniform.png",
    "./vegeta_blue_heavy_uniform.png",
    "./vegeta_blue_idle_uniform.png",
    "./vegeta_blue_kibomb_fx_uniform.png",
    "./vegeta_blue_koma1_uniform.png",
    "./vegeta_blue_koma2_uniform.png",
    "./vegeta_blue_koma3_uniform.png",
    "./vegeta_blue_koma4_uniform.png",
    "./vegeta_blue_light_uniform.png",
    "./vegeta_blue_super_galick_uniform.png",
    "./vegeta_blue_teleport_uniform.png",
    "./vegeta_blue_transformation_uniform.png",
    "./vegeta_blue_up_attack_uniform.png",
    "./vegeta_blue_up_uniform.png",
    "./vegeta_ssj_air_uniform.png",
    "./vegeta_ssj_back_dash_uniform.png",
    "./vegeta_ssj_bigbang_fx_uniform.png",
    "./vegeta_ssj_blue_run_uniform.png",
    "./vegeta_ssj_charge_uniform.png",
    "./vegeta_ssj_combo_attack_uniform.png",
    "./vegeta_ssj_dash_uniform.png",
    "./vegeta_ssj_diag_galick_cast_uniform.png",
    "./vegeta_ssj_diag_galick_fx_uniform.png",
    "./vegeta_ssj_down_air_uniform.png",
    "./vegeta_ssj_finalflash_beam_uniform.png",
    "./vegeta_ssj_finalflash_impact_uniform.png",
    "./vegeta_ssj_galick_cast_uniform.png",
    "./vegeta_ssj_galick_fx_uniform.png",
    "./vegeta_ssj_gaurd_uniform.png",
    "./vegeta_ssj_heavy_uniform.png",
    "./vegeta_ssj_hit_uniform.png",
    "./vegeta_ssj_idle_uniform.png",
    "./vegeta_ssj_jump_uniform.png",
    "./vegeta_ssj_knock_down_uniform.png",
    "./vegeta_ssj_light_uniform.png",
    "./vegeta_ssj_run_uniform.png",
    "./vegeta_ssj_self_explosion_uniform.png",
    "./vegeta_ssj_super_kick_uniform.png",
    "./vegeta_ssj_super_up_fx_uniform.png",
    "./vegeta_ssj_super_up_uniform.png",
    "./vegeta_ssj_transformation_uniform.png",
    "./vegeta_ssj_up_special_uniform.png",
    "./vegeta_ssj_up_uniform.png",
  ],
  yuji: [
    "./yuji_ball_impact_uniform.png",
    "./yuji_ball_proj_uniform.png",
    "./yuji_beam_proj_uniform.png",
    "./yuji_ground_fx_uniform.png",
    "./yuji_koma_burst_uniform.png",
    "./yuji_koma_finfx_uniform.png",
    "./yuji_pillar_fx.png",
    "./yuji_sukuna_slahs_effect.png",
  ],
  zaraki: [
    "./zaraki_Yachiru_Kusajishi_dash_assist_uniform.png",
    "./zaraki_Yachiru_Kusajishi_throw_projectile_uniform.png",
    "./zaraki_specail_effect_assist_uniform.png",
    "./zaraki_special_effect_uniform.png",
  ],
};

// Union of FX sheets for the given roster keys, deduped. Unknown keys contribute nothing.
export function fxSheetsForFighters(...rosterKeys) {
  const out = new Set();
  for (const k of rosterKeys) for (const p of (FX_SHEETS_BY_CHAR[k] || [])) out.add(p);
  return [...out];
}
