import { chromium } from "playwright";
import http from "node:http"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
const R = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MIME={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".css":"text/css",".png":"image/png",".mp3":"audio/mpeg",".json":"application/json"};
const server=await new Promise(r=>{const s=http.createServer((q,res)=>{const u=decodeURIComponent(q.url.split("?")[0]);const f=path.join(R,u==="/"?"/index.html":u);if(!f.startsWith(R)){res.writeHead(403).end();return;}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404).end();return;}res.writeHead(200,{"content-type":MIME[path.extname(f)]||"application/octet-stream"});res.end(d);});});s.listen(0,"127.0.0.1",()=>r(s));});
const base=`http://127.0.0.1:${server.address().port}`;
const b=await chromium.launch({headless:true,args:["--autoplay-policy=no-user-gesture-required"]});
const page=await b.newPage({viewport:{width:1280,height:720}});
const st=()=>page.evaluate(()=>window.__harness.state());
const vfx=()=>page.evaluate(()=>window.__harness.obitoVoidFX());
async function wf(n){const s=(await st()).frame;await page.waitForFunction(([a,b])=>window.__harness.state().frame>=a+b,[s,n],{timeout:15000,polling:16});}
let P=0,F=0;const ck=(n,c,d="")=>{(c?P++:F++);console.log(`  ${c?"✅":"❌"} ${n}${d?`  — ${d}`:""}`);};
await page.goto(`${base}/index.html?harness=1&p1=obito`,{waitUntil:"load"});
await page.waitForFunction(()=>!!window.__harness,null,{timeout:15000});
await page.mouse.click(640,360);
await page.evaluate(()=>{window.__harness.start();window.__harness.skipToBattle();});
await wf(20);
await page.evaluate(()=>{window.__harness.setSkin?.("p1","obitoVoid");window.__harness.setP2X?.(99999);});
await wf(12);
let v=await vfx();
ck("Void FX seeded (26 dots + 3 swirls)",v.seeded&&v.dots===26&&v.swirls===3,`dots=${v.dots} swirls=${v.swirls} skinId=${v.skinId}`);
ck("overlay animates (clock advancing → it's drawing)",v.clock>5,`clock=${v.clock}`);
ck("tracks the sprite bbox",v.rect.x!=null&&v.rect.w!=null,`rect=${JSON.stringify(v.rect)}`);
const x0=v.rect.x;
await page.keyboard.down("a");await wf(10);await page.keyboard.up("a");
const v2=await vfx();
ck("bbox FOLLOWS the fighter when he moves",Math.abs(v2.rect.x-x0)>10,`x0=${Math.round(x0)} x1=${Math.round(v2.rect.x)}`);
// intangibility activation — FX must keep tracking
await page.waitForFunction(()=>window.__harness.p1().grounded,null,{timeout:4000}).catch(()=>{});
await page.evaluate(()=>window.__harness.obitoKamuiToggle());
await wf(6);
const k=await page.evaluate(()=>window.__harness.obitoKamui());
const v3=await vfx();
ck("Void FX still tracks DURING intangibility (phased)",k.phased&&v3.rect.x!=null&&v3.clock>v2.clock,`phased=${k.phased} clock=${v3.clock}`);
await page.evaluate(()=>window.__harness.setP2X?.(99999));
await page.screenshot({path:path.join(R,"harness/shots/obito_void_overlay.png")});
console.log(`\nRESULT ${P} pass / ${F} fail`);
await b.close();server.close();process.exit(F?1:0);
