#!/usr/bin/env python3
"""Emit borutoVoice.js — TWO SEPARATE voice pools (base form + Momoshiki Karma form), assignment by
ACOUSTIC SIGNAL ONLY (duration/loudness via analyze_boruto_voice.py; clips are UNIDENTIFIED JA, no
transcript). Maps clip-numbers → pools and globs each to its exact filename so names are never mistyped.
Base sub-clips (flagged long clips split at silence gaps) are referenced as boruto_main_<NNNx>.mp3."""
import glob, os
ROOT = os.path.join(os.path.dirname(__file__), "..")

def fn(pool, n):
    if any(c.isalpha() for c in n):                      # split sub-clip e.g. 019b → boruto_main_019b.mp3
        return f"boruto_{pool}_{n}.mp3"
    hits = glob.glob(os.path.join(ROOT, f"boruto_{pool}_{n}_*.mp3"))
    return os.path.basename(hits[0]) if hits else None

# ── BASE FORM pools (163 clips + 23 split sub-lines) ──────────────────────────────────────────────
BASE = {
  "intro":        ["001","007","024","025","030","050","059","082","122","123"],
  "lightEffort":  ["003","011","046","103","118","124","130","134","153","162"],
  "heavy":        ["015","016","020","026","027","031","140","144"],
  "rasenganGround":["006","010","021","033","055","057"],
  "rasenganAir":  ["075","081","084","085","145","146"],
  "vanishing":    ["060","061","063","091","094"],
  "shiden":       ["018","023","038","051","086","045","058"],
  "windWater":    ["088","089","108","117","076","087"],
  "shadowClone":  ["120","126","128","131","142"],
  "throwWeapon":  ["035","036","039","040","043","062"],
  "ult":          ["041","002","012","019b","047b","028a","052b","077b"],   # longest/most dramatic (whole gap-masked + split segments)
  "hitLight":     ["080","096","109","111","139","152","137","079","157","161"],
  "hitHeavy":     ["099","115","132","133","135","138","147","148"],
  "knockdown":    ["072","073","074","093","100","112","136","154"],
  "win":          ["009","013","022","029","034","042","078","155","092","102"],
  # NAMECALL: no clip identifiable as just his name (no transcript) → intentionally UNMAPPED (folded into intro).
}

# ── MOMOSHIKI KARMA FORM pools (49 clips — COMPLETELY SEPARATE from base) ──────────────────────────
# Priority: transformation activation (dramatic) + absorb SUCCESS vs FAILURE (audibly distinct — different
# files, different acoustic signature: success = mid confident ~2.6-3.1s f0~150; fail = short strained
# ~0.6-1.4s f0~300+). All acoustic-only (UNIDENTIFIED) — flagged for by-ear confirmation.
KARMA = {
  "transform":     ["011","049","004","022","005"],   # loudest/longest/most dramatic → Momoshiki taking hold
  "absorbSuccess": ["008","002","048","024","006"],    # mid confident casts
  "absorbFail":    ["034","040","038","033"],          # short strained/high-tension grunts (DISTINCT from success)
  "hit":           ["023","036","037","047","009","015","029"],   # transformed hit reactions
  "revert":        ["030","035"],                       # soft/strained "losing control" reversion
}

HEADER = '''// borutoVoice.js
// ---------------------------------------------------------------------------
// Boruto Uzumaki voice-line pools (audio-only; NO gameplay effect). TWO COMPLETELY SEPARATE pools:
//   BORUTO_VOICE       — BASE form (boruto_main_*.mp3, 163 clips + 23 split sub-lines)
//   BORUTO_KARMA_VOICE — MOMOSHIKI KARMA form (boruto_karma_*.mp3, 49 clips) — NEVER mixed with base.
// Clips are UNIDENTIFIED JAPANESE (silence-gap segmented from source compilations; no transcript/translation
// possible), so assignment is by ACOUSTIC SIGNAL ONLY (duration / loudness / pitch via
// tools/analyze_boruto_voice.py → boruto_{main,karma}_voice_analysis.tsv), NOT by content — FLAGGED for
// by-ear confirmation. pickBorutoVoice(pool) / pickBorutoKarmaVoice(pool) return ONE clip at random; callers
// play via sound.playSfxFile(clip, null).
//
// FLAGGED LONG BASE CLIPS: the 12 clips flagged as 7-11s (likely multi-line, music-masked pauses) were
// gap-analyzed; the 9 with detectable internal gaps were SPLIT at gap midpoints → boruto_main_<NNNx>.mp3
// (a/b/c segments). The 3 with NO detectable gaps (002/012/041 — music fully masks the pauses) are kept
// WHOLE and used only in the ULT pool (a long dramatic line is fine there). Re-cut by ear if boundaries surface.
//
// KARMA success/failure ARE audibly distinct (different files + different acoustic signature): absorbSuccess
// = mid confident clips (~2.6-3.1s, f0~150Hz); absorbFail = short strained/high-tension grunts (~0.6-1.4s,
// f0~300Hz+). Generated by tools/gen_boruto_voice_js.py.
// ---------------------------------------------------------------------------
'''

def emit(varname, pools, prefix):
    lines = [f"export const {varname} = {{"]
    for pool, nums in pools.items():
        files = [fn(prefix, n) for n in nums]
        miss = [n for n, f in zip(nums, files) if not f]
        if miss: raise SystemExit(f"MISSING files for {varname}.{pool}: {miss}")
        arr = ", ".join(f'"./{f}"' for f in files)
        lines.append(f"  {pool}: [{arr}],")
    lines.append("}")
    return "\n".join(lines)

if __name__ == "__main__":
    out = os.path.join(ROOT, "borutoVoice.js")
    body = [HEADER,
            emit("BORUTO_VOICE", BASE, "main"), "",
            emit("BORUTO_KARMA_VOICE", KARMA, "karma"), "",
            "export function pickBorutoVoice(pool) {",
            "  const arr = BORUTO_VOICE[pool]",
            "  if (!Array.isArray(arr) || arr.length === 0) return null",
            "  return arr[Math.floor(Math.random() * arr.length)]",
            "}", "",
            "export function pickBorutoKarmaVoice(pool) {",
            "  const arr = BORUTO_KARMA_VOICE[pool]",
            "  if (!Array.isArray(arr) || arr.length === 0) return null",
            "  return arr[Math.floor(Math.random() * arr.length)]",
            "}", ""]
    with open(out, "w") as fh: fh.write("\n".join(body))
    nb = sum(len(v) for v in BASE.values()); nk = sum(len(v) for v in KARMA.values())
    print(f"wrote {out}: BASE {len(BASE)} pools/{nb} slots, KARMA {len(KARMA)} pools/{nk} slots")
