// tools/stamp_version.mjs
// ─────────────────────────────────────────────────────────────────────────────
// CACHE-BUSTING for the raw-ES-module app (no bundler). Because index.html loads
// `game.js` which STATICALLY imports 60+ sibling modules, versioning only the
// entry does nothing for the graph. So we emit an <script type="importmap"> that
// remaps every local module URL → `<url>?v=<hash>`, plus a versioned entry. The
// browser cache-keys on the full URL (incl. query), so a new build = new hash =
// new URLs = guaranteed-fresh fetch — on local dev AND on GitHub Pages (kills the
// deploy-lag stale-module class of bug).
//
// The version is a CONTENT HASH of the module graph (not the git commit hash):
// it changes IFF a module's bytes change — so it busts exactly when needed, works
// for uncommitted local edits (no commit required), and can't be forgotten.
//
// USAGE:
//   node tools/stamp_version.mjs      → stamp index.html in place (run by the pre-commit hook)
//   (import buildModuleBlock/injectBlock from the dev server for live injection)
// ─────────────────────────────────────────────────────────────────────────────
import fs from "node:fs"; import path from "node:path"; import crypto from "node:crypto"; import { fileURLToPath } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const MARK_START = "<!-- BUILD:MODULES START (auto-generated by tools/stamp_version.mjs — do not edit by hand) -->";
export const MARK_END   = "<!-- BUILD:MODULES END -->";

// The local ES-module graph the browser fetches: every root-level *.js, PLUS any
// ./sub/dir.(js|mjs) specifier referenced from them (static or dynamic import).
export function collectModules() {
  const roots = fs.readdirSync(REPO).filter(f => f.endsWith(".js") && fs.statSync(path.join(REPO, f)).isFile());
  const set = new Set(roots.map(f => "./" + f));
  const specRe = /(?:from|import)\s*\(?\s*["'](\.\/[^"']+\.m?js)["']/g;
  for (const f of roots) {
    const src = fs.readFileSync(path.join(REPO, f), "utf8");
    let m; while ((m = specRe.exec(src))) set.add(m[1]);
  }
  return [...set].filter(s => fs.existsSync(path.join(REPO, s.slice(2)))).sort();
}

export function computeVersion(modules = collectModules()) {
  const h = crypto.createHash("sha256");
  for (const m of modules) h.update(m).update(fs.readFileSync(path.join(REPO, m.slice(2))));
  return h.digest("hex").slice(0, 10);
}

// The generated HTML block: the import map (every module → ?v=hash) + the versioned entry script.
export function buildModuleBlock(entry = "./game.js") {
  const modules = collectModules();
  const version = computeVersion(modules);
  const imports = {};
  for (const m of modules) imports[m] = `${m}?v=${version}`;
  const map = JSON.stringify({ imports }, null, 6);
  const html =
`${MARK_START}
    <script type="importmap">
    ${map}
    </script>
    <script type="module" src="${entry}?v=${version}"></script>
    ${MARK_END}`;
  return { version, html, modules };
}

// Insert/replace the generated block in an index.html string (idempotent).
// The markers are LITERAL text (they contain regex metachars like ( ) . ), so escape them
// before building the region matcher — an unescaped RegExp silently fails to match.
const _rx = s => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
export function injectBlock(html, block) {
  const region = new RegExp(`${_rx(MARK_START)}[\\s\\S]*?${_rx(MARK_END)}`);
  if (region.test(html)) return html.replace(region, block);
  // First run: swap the legacy plain entry <script> for the marked block.
  return html.replace(/[ \t]*<script type="module" src="\.\/game\.js"><\/script>/, "    " + block);
}

function stampIndexHtml() {
  const idx = path.join(REPO, "index.html");
  const { html: block, version, modules } = buildModuleBlock();
  const out = injectBlock(fs.readFileSync(idx, "utf8"), block);
  fs.writeFileSync(idx, out);
  console.log(`stamped index.html → v=${version}  (${modules.length} modules)`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) stampIndexHtml();
